name: quran
description: Flutter Quran Project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  go_router: ^11.1.2
  google_fonts: ^6.1.0
  just_audio: ^0.9.35
  riverpod_annotation: ^2.2.0
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.0
flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: fonts/Poppins-Thin.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Black.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 900
    - family: LPMQ Isep Misbah
      fonts:
        - asset: fonts/LPMQ.ttf
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
